### ISSUE TITLE
make_fea needs cursive attach support

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/font-ttf-scripts#10]
Need mechanism in make_fea to generate GPOS Type 3 cursive attach lookups.

**Comment by nrsiward** [comment]
We should consider whether this feature is best implemented in FontUtils or in the makeFea we might implement in pysilfont (especially since makeGdl.py already exists).

**Comment by bobh0303** [comment]
We have agreed that, while waiting for a python-based make_fea replacement, to proceed with adding cursive support to make_fea (and probably make_gdl will get it too). 

I propose to add a single option to name the cursive entry and exit APs, as follows:
```
  --cursive "entryAP,exitAP"
```

Comments invited.

**Comment by mhosken** [comment]
Looks good. We should make sure that --cursive is repeatable, not that I can think of a use case for repeating, at the moment.

**Comment by bobh0303** [comment]
Implemented in 191cc5e2eb39121d72a32b6ba66dc550d5612111
