### ISSUE TITLE
ttftable update, delete or import not work

### ISSUE THREAD

**Issue by ghost** [silnrsi/font-ttf-scripts#17]
ttftable -l -v font.ttf list graphite tables, export works but it's not possible to update, delete or import.
What am I doing wrong? 
ttftable -delete Gloc font.ttf is not removing the table. Any table is never removed.
ttftable -import "Gloc=font.gloc.dat" font.ttf is never overwrited or updated.

md5sum shows my font.ttf is never edited.

**Comment by bobh0303** [comment]
Try supplying an output font file name. So, for example,
```
 ttftable -delete Gloc font.ttf outputfont.ttf
```
Like most scripts in this package, `ttftable` does not do in-place file modification.

**Comment by ghost** [comment]
it worked. Do I need to set the checksum after import the table once is modified? It's from a dumb mutator and modifies the binary table.

**Comment by bobh0303** [comment]
The checksum(s) for your imported table(s) should be correct, as should the font-wide checksum. Let us know if you discover otherwise.

**Comment by bobh0303** [comment]
This was user error, not a bug or enhancement request.
